#ifndef SFML_TEMPLATE_STATEIDENTIFIERS_HPP
#define SFML_TEMPLATE_STATEIDENTIFIERS_HPP

namespace States {
  enum ID {
    NONE,
    TITLE,
    GAME,
    PAUSE,
    GAME_OVER,
    NEW_HIGHSCORE,
    SETTINGS,
    STORE,
    LEVEL_FINISHED
  };
}

#endif //SFML_TEMPLATE_STATEIDENTIFIERS_HPP